# Generated by Django 3.0.5 on 2020-07-08 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_skills'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skills',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='skills',
            name='author',
        ),
        migrations.DeleteModel(
            name='MyProjects',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
